apiVersion: batch/v1
kind: Job
metadata:
  name: test
  labels:
    runboat/job-kind: test
spec:
  template:
    metadata:
      labels:
        runboat/job-kind: test
    spec:
      enableServiceLinks: false
      containers:
        - name: test
          image: odoo
          volumeMounts:
            - name: runboat-scripts
              mountPath: /runboat
            - name: data
              mountPath: /mnt/data
          envFrom:
            - secretRef:
                name: odoosecretenv
            - configMapRef:
                name: odooenv
          args: ["bash", "/runboat/runboat-test.sh"]
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: runboat-scripts
          configMap:
            name: runboat-scripts
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Never
  completions: 1
  backoffLimit: 0
  activeDeadlineSeconds: 1800
